/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comment-ca-marche'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comment-ca-marche'
  id: '__root__' | '/' | '/comment-ca-marche'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
